version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.5
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.5
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: debezium/connect:0.9
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses 
# For testing newer connector versions, unpack the connector archive into this
# directory and uncomment the lines below
    volumes:
      - ./debezium-connector-mongodb:/kafka/connect/debezium-connector-mongodb
  
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:3.6
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]