version: "3"

services:
  namenode:
    image: longpt233/hadoop-spark:2.0.0
    container_name: hadoop-master   # = host name = core-site 
    hostname: cluster-172-25-0-2
    ports: 
      - 8088:8088    # ui yarn
      - 4040:4040   # ui spark 
      - 9870:9870   # ui name node  
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.2

  datanode1:
    image: longpt233/hadoop-base:2.0.0
    container_name: hadoop-slave1   # phai tuong ung voi file worker ben trong 
    hostname: cluster-172-25-0-3
    tty: true
    ports:  
      - 9864:9864
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.3

  datanode2:
    image: longpt233/hadoop-base:2.0.0
    container_name: hadoop-slave2 
    hostname: cluster-172-25-0-4
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.4

networks:
    cluster-hadoop:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16