version: "3"

services:
  namenode:
    image: longpt233/hadoop-secure:0.0.1
    container_name: dragonsecure   # = host name = core-site 
    hostname: hadoop110
    ports: 
      - 50070:50070   # ui name node  
      - 9864:9864
      - 9870:9870
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.1.10

  nifi:
    image: longpt233/nifi:0.0.1
    container_name: dragonnifi   # = host name = core-site 
    hostname: hadoop111
    ports: 
      - 8080:8080
    volumes:
      # - ./nifi/conf/flow.json.gz:/opt/nifi/conf/flow.json.gz
      # - ./nifi/conf/flow.xml.gz:/opt/nifi/conf/flow.xml.gz
       - ./nifi/conf:/opt/nifi/conf

    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.1.11

  unsecure:
    image: longpt233/hadoop-insecure:0.0.1
    container_name: dragoninsecure
    hostname: hadoop112
    ports:
      - "50071:50070" # datanode
      - "50075:50075" # namenode
      - "9871:9870"   # for 3x
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.1.12

networks:
    cluster-hadoop:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16
