version: '3.7'
services:
  postgres:
    image: 'postgres:15'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    # thấy bảo là postgres 16+ là có thể đọc cdc debezium từ con rep (trước đó thì phải đọc từ promary thôi)
    # wal_level=replica -> WARNING:  wal_level is insufficient to publish logical changes
    # trong doc nó cx bảo là phải set về logical
    # wal_level determines how much information is written to the WAL
    # minimal -> replica (default) -> logical (thêm decode để làm gì nhỉ)
    command: |
      postgres 
      -c wal_level=logical 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    # healthcheck:
    #   test: [ 'CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1' ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - my-network

  minio:
    image: 'minio/minio:RELEASE.2024-10-02T17-50-41Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my-network

  # mc-init:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 10 &&
  #     mc alias set myminio http://minio:9000 minio minio123 &&
  #     mc mb myminio/hive || true 
  #     "
  #   networks:
  #     - my-network

volumes:
  minio-data:
    driver: local
  # docker volume ls
  # docker volume inspect minio-data
  # ls /var/lib/docker/volumes/minio-data/_data

networks:
  my-network:
    driver: bridge