version: "3"

services:
 # Flink Job Manager
  jobmanager:
    image: flink:1.20
    container_name: jobmanager
    environment:
      # - JOB_MANAGER_RPC_ADDRESS=jobmanager
      # - HADOOP_CLASSPATH='hadoop classpath'
      # - AWS_ACCESS_KEY_ID=minio
      # - AWS_SECRET_ACCESS_KEY=minio123
      # - AWS_REGION=us-east-1
      # - AWS_DEFAULT_REGION=us-east-1
      # - S3_ENDPOINT=http://10.208.164.167:9000
      # - S3_PATH_STYLE_ACCESS=true
      # - FLINK_LOG_LEVEL=DEBUG   -> ROOT_LOG_LEVEL ?
      # https://www.decodable.co/blog/troubleshooting-flink-sql-s3-problems -> bypass fs.s3a.access.key ???????
      - 'NO_PROXY=localhost,127.0.0.1,10.208.164.167'
      - 'no_proxy=localhost,127.0.0.1,10.208.164.167'
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        fs.s3a.endpoint: http://10.208.164.167:9000
        fs.s3a.path.style.access: true
        fs.s3a.access.key: minio
        fs.s3a.secret.key: minio123
    extra_hosts:
      - "hive-metastore:10.208.164.167"
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
    # lib cdc
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/paimon-flink-1.20-0.9.0.jar:/opt/flink/lib/paimon-flink-1.20-0.9.0.jar
      - ./jars/flink-sql-connector-postgres-cdc-3.2.1.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-3.2.1.jar
    # lib s3
      - ./jars/paimon-s3-0.9.0.jar:/opt/flink/lib/paimon-s3-0.9.0.jar
      - ./jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.0.jar
      # - ./jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      # - ./jars/paimon-flink-action-0.8.1.jar:/opt/flink/lib/paimon-flink-action-0.8.1.jar
      # - ./hive-site.xml:/opt/flink/conf/hive-site.xml
      - ./log4j.properties:/opt/flink/conf/log4j.properties
    deploy:
          replicas: 1
    networks:
      paimon-network:
        ipv4_address: 172.27.2.10
  

  taskmanager:
    image: flink:1.20
    environment:
      # - JOB_MANAGER_RPC_ADDRESS=jobmanager
      # - HADOOP_CLASSPATH='hadoop classpath'
      # - AWS_ACCESS_KEY_ID=minio
      # - AWS_SECRET_ACCESS_KEY=minio123
      # - AWS_REGION=us-east-1
      # - AWS_DEFAULT_REGION=us-east-1
      # - S3_ENDPOINT=http://10.208.164.167:9000
      # - S3_PATH_STYLE_ACCESS=true
      # - FLINK_LOG_LEVEL=DEBUG
      - 'NO_PROXY=localhost,127.0.0.1,10.208.164.167'
      - 'no_proxy=localhost,127.0.0.1,10.208.164.167'
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        fs.s3a.endpoint: http://10.208.164.167:9000
        fs.s3a.path.style.access: true
        fs.s3a.access.key: minio
        fs.s3a.secret.key: minio123
    extra_hosts:
      - "hive-metastore:10.208.164.167"
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
    # lib cdc
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/paimon-flink-1.20-0.9.0.jar:/opt/flink/lib/paimon-flink-1.20-0.9.0.jar
      - ./jars/flink-sql-connector-postgres-cdc-3.2.1.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-3.2.1.jar
    # lib s3
      - ./jars/paimon-s3-0.9.0.jar:/opt/flink/lib/paimon-s3-0.9.0.jar
      - ./jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.0.jar
      # - ./jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      # - ./jars/paimon-flink-action-0.8.1.jar:/opt/flink/lib/paimon-flink-action-0.8.1.jar
      # - ./hive-site.xml:/opt/flink/conf/hive-site.xml
      - ./log4j.properties:/opt/flink/conf/log4j.properties
    deploy:
          replicas: 2
    networks: 
      - paimon-network

networks:
  paimon-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.2.0/24