services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.3.2
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://10.208.164.167:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:

    debezium:
        image: quay.io/debezium/connect:2.2
        environment:
            BOOTSTRAP_SERVERS: kafka:29092
            GROUP_ID: 1
            CONFIG_STORAGE_TOPIC: connect_configs
            STATUS_STORAGE_TOPIC: connect_statuses
            OFFSET_STORAGE_TOPIC: connect_offsets
            KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
            VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        depends_on: [ kafka ]
        healthcheck:
          test:
            [ 'CMD', 'curl', '--silent', '--fail', '-X', 'GET', 'http://localhost:8083/connectors', ]
          start_period: 10s
          interval: 10s
          timeout: 5s
          retries: 5
        ports:
            - "8083:8083"
        # volume   ... thêm các thư viện cần thiết vô đây

    debezium-ui:
      image: debezium/debezium-ui:latest
      container_name: debezium-ui
      hostname: debezium-ui
      depends_on:
        debezium:
          condition: service_healthy
      ports:
        - '8080:8080'
      environment:
        KAFKA_CONNECT_URIS: http://debezium:8083
