version: '3.7'
services:
  hive-metastore:
    image: 'longpt233/hms:0.0.1'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    # volumes:
      # - ./hms/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      # ERROR XBM0H: Directory /opt/metastore_db cannot be created.  -> khogn hieu sao bao loi nay  mac du van co db trong postgres- chưa mount được folder -> ccopy tay vậy
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres

