version: '3.7'
services:
  postgres:
    image: 'postgres:15'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    networks:
      - my-network

  hive-metastore:
    image: 'longpt233/hms:0.0.1'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    # volumes:
      # - ./hms/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      # ERROR XBM0H: Directory /opt/metastore_db cannot be created.  -> khogn hieu sao bao loi nay  mac du van co db trong postgres- chưa mount được folder -> ccopy tay vậy
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres
    networks:
      - my-network

  minio:
    image: 'minio/minio:RELEASE.2024-10-02T17-50-41Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - my-network

volumes:
  minio-data:
    driver: local
  # docker volume ls
  # docker volume inspect minio-data
  # ls /var/lib/docker/volumes/minio-data/_data

networks:
  my-network:
    driver: bridge