build: 
	@docker build -f ./hms/Dockerfile -t longpt233/hms:0.0.1 .

get: 
	@echo "download"
	bash get_jar.sh
	# @wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar 
	# @wget https://repo.maven.apache.org/maven2/org/apache/paimon/paimon-flink-1.18/0.8.1/paimon-flink-1.18-0.8.1.jar
	# @wget https://repo.maven.apache.org/maven2/org/apache/paimon/paimon-flink-action/0.8.1/paimon-flink-action-0.8.1.jar 

